import pytest
import httpx
from unittest.mock import AsyncMock, MagicMock, patch
from app.agent.narrative import generate_narrative

@pytest.mark.anyio
async def test_narrative_success():
    mock_response_data = {
        "message": {"content": '{"summary": "This is a valid test summary generated by the model successfully."}'},
        "eval_count": 25,
        "prompt_eval_count": 50
    }
    
    # Configure a MagicMock for the HTTP response so its methods return normal values/dicts
    mock_resp = MagicMock()
    mock_resp.status_code = 200
    mock_resp.json.return_value = mock_response_data
    mock_resp.raise_for_status = MagicMock()

    with patch("httpx.AsyncClient.post", new_callable=AsyncMock) as mock_post:
        mock_post.return_value = mock_resp
        
        result = await generate_narrative(["Found minor security flaw."])
        assert result["fallback_used"] is False
        assert "valid test summary" in result["summary"]
        assert result["eval_count"] == 25

@pytest.mark.anyio
async def test_narrative_connection_refused():
    with patch("httpx.AsyncClient.post", side_effect=httpx.ConnectError("Connection refused")):
        result = await generate_narrative(["Some finding."])
        assert result["fallback_used"] is True
        assert "Summary of findings" in result["summary"]