import pytest
import httpx
from unittest.mock import AsyncMock, patch
from app.agent.narrative import generate_narrative, NarrativeOutput

@pytest.mark.anyio
async def test_narrative_success():
    mock_response = {
        "message": {"content": '{"summary": "This is a valid test summary generated by the model successfully."}'},
        "eval_count": 25,
        "prompt_eval_count": 50
    }
    
    with patch("httpx.AsyncClient.post", new_callable=AsyncMock) as mock_post:
        mock_post.return_value.status_code = 200
        mock_post.return_value.json.return_value = mock_response
        
        result = await generate_narrative(["Found minor security flaw."])
        assert result["fallback_used"] is False
        assert "valid test summary" in result["summary"]
        assert result["eval_count"] == 25

@pytest.mark.anyio
async def test_narrative_connection_refused():
    with patch("httpx.AsyncClient.post", side_effect=httpx.ConnectError("Connection refused")):
        result = await generate_narrative(["Some finding."])
        assert result["fallback_used"] is True
        assert "Summary of findings" in result["summary"]