"""Integration adapters, identity resolution, and external clients."""

from app.integrations.errors import (
    AuthError,
    IntegrationError,
    IntegrationTimeoutError,
    NotFoundError,
    RateLimitError,
    UpstreamError,
)
from app.integrations.github import GitHubClient
from app.integrations.github_normalizer import (
    NormalizationCounts,
    clean_excerpt,
    ingest_commits,
    ingest_pull_requests,
    ingest_repositories,
    ingest_reviews,
    normalize_commit,
    normalize_pull_request,
    normalize_repository,
    normalize_review,
    upsert_commit,
    upsert_pull_request,
    upsert_repository,
    upsert_review,
)
from app.integrations.http import HttpClient
from app.integrations.identity_loader import (
    IdentityMapError,
    load_identity_map,
    parse_identity_map,
)
from app.integrations.identity_resolver import (
    attribute_commits,
    attribute_pull_requests,
    attribute_reviews,
    attribute_work_items,
    record_inferred_link,
    record_unmatched,
    resolve_actor,
)
from app.integrations.jira import JiraClient
from app.integrations.jira_normalizer import (
    extract_blocking_dependencies,
    ingest_dependencies,
    ingest_projects,
    ingest_work_items,
    is_issue_flagged,
    map_status,
    normalize_project,
    normalize_work_item,
    upsert_project,
    upsert_work_item,
    upsert_work_item_dependency,
)
from app.integrations.link_builder import (
    extract_ticket_keys,
    link_commit,
    link_jira_remote_links,
    link_pull_request,
    upsert_work_item_link,
)

__all__ = [
    "AuthError",
    "GitHubClient",
    "HttpClient",
    "IdentityMapError",
    "IntegrationError",
    "IntegrationTimeoutError",
    "JiraClient",
    "NormalizationCounts",
    "NotFoundError",
    "RateLimitError",
    "UpstreamError",
    "attribute_commits",
    "attribute_pull_requests",
    "attribute_reviews",
    "attribute_work_items",
    "clean_excerpt",
    "extract_blocking_dependencies",
    "extract_ticket_keys",
    "ingest_commits",
    "ingest_dependencies",
    "ingest_projects",
    "ingest_pull_requests",
    "ingest_repositories",
    "ingest_reviews",
    "ingest_work_items",
    "is_issue_flagged",
    "link_commit",
    "link_jira_remote_links",
    "link_pull_request",
    "load_identity_map",
    "map_status",
    "normalize_commit",
    "normalize_project",
    "normalize_pull_request",
    "normalize_repository",
    "normalize_review",
    "normalize_work_item",
    "parse_identity_map",
    "record_inferred_link",
    "record_unmatched",
    "resolve_actor",
    "upsert_commit",
    "upsert_project",
    "upsert_pull_request",
    "upsert_repository",
    "upsert_review",
    "upsert_work_item",
    "upsert_work_item_dependency",
    "upsert_work_item_link",
]
